default: cpsc2150/extendedConnectX/models/*.java cpsc2150/extendedConnectX/GameScreen.java
	javac cpsc2150/extendedConnectX/models/*.java cpsc2150/extendedConnectX/GameScreen.java
	
run: cpsc2150/extendedConnectX/models/*.class cpsc2150/extendedConnectX/GameScreen.java
	java cpsc2150.extendedConnectX.GameScreen
	
clean: 
	rm -f cpsc2150/extendedConnectX/models/*.class
	rm -f cpsc2150/extendedConnectX/*.class